"""empty message

Revision ID: d41cbcc69061
Revises: 35ff6bd42ce5
Create Date: 2025-05-14 18:31:42.972422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd41cbcc69061'
down_revision = '35ff6bd42ce5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cat_photo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto', sa.Text(), nullable=True))
        batch_op.drop_column('foto2')
        batch_op.drop_column('foto5')
        batch_op.drop_column('foto3')
        batch_op.drop_column('foto4')
        batch_op.drop_column('foto1')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cat_photo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto1', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('foto4', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('foto3', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('foto5', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('foto2', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('foto')

    # ### end Alembic commands ###
